# Generated by Django 5.1.15 on 2026-02-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0099_usermemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchmodelconfig",
            name="bi_encoder_dimensions",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
