# Generated by Django 5.1.15 on 2026-02-16 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0101_organization_team_teammembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpServiceRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("server_url", models.URLField(max_length=500)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        max_length=20,
                    ),
                ),
                (
                    "oauth_discovery_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "oauth_client_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("oauth_client_secret", models.TextField(blank=True, null=True)),
                (
                    "oauth_scopes",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "supports_dcr",
                    models.BooleanField(default=False, help_text="Dynamic Client Registration"),
                ),
                ("requires_admin_approval", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                ("icon_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="McpUserConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scopes_granted",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team this agent belongs to (for team-scoped agents)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="database.team",
            ),
        ),
        migrations.AddField(
            model_name="apollosuser",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Display name from identity provider",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apollosuser",
            name="entra_oid",
            field=models.CharField(
                blank=True,
                help_text="Microsoft Entra ID Object ID (stable across app registrations)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="apollosuser",
            name="entra_upn",
            field=models.CharField(
                blank=True,
                help_text="Microsoft Entra ID User Principal Name",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apollosuser",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time Entra ID group memberships were synced",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="shared_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who shared this entry (if promoted from personal)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team this entry belongs to (required when visibility=team)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="database.team",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("team", "Team"),
                    ("org", "Organization"),
                ],
                db_index=True,
                default="private",
                help_text="Access level: private (owner only), team, or org-wide",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="entra_tenant_id",
            field=models.CharField(
                blank=True,
                help_text="Microsoft Entra ID Tenant ID for SSO",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="entra_group_id",
            field=models.CharField(
                blank=True,
                help_text="Microsoft Entra ID Security Group ID for team sync",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("team", "Team"),
                    ("org", "Organization"),
                    ("public", "Public"),
                    ("protected", "Protected"),
                ],
                default="private",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["visibility", "team"], name="idx_entry_visibility_team"),
        ),
        migrations.AddField(
            model_name="mcpserviceregistry",
            name="allowed_teams",
            field=models.ManyToManyField(blank=True, related_name="allowed_mcp_services", to="database.team"),
        ),
        migrations.AddField(
            model_name="mcpuserconnection",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_connections",
                to="database.mcpserviceregistry",
            ),
        ),
        migrations.AddField(
            model_name="mcpuserconnection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcp_connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mcpuserconnection",
            unique_together={("user", "service")},
        ),
    ]
